### ISSUE TITLE
multiple task hung in `context_switch()`

### ISSUE THREAD

**Issue by xingyiz** [sched-ext/sched_ext#131] opened 2024-01-29 06:58 UTC
Multiple task hungs were detected in BPF and RCU functions when running sched_ext with syzkaller. These functions precede `context_switch` where the actual hang occurs. Some of the functions include:

- `bpf_prog_pack_free+0x28/0x300 sched_ext/kernel/bpf/core.c:941`
- `__bpf_arch_text_poke+0x141/0x350 sched_ext/arch/x86/net/bpf_jit_comp.c:424`
- `text_poke_set+0x4d/0xf0 sched_ext/arch/x86/kernel/alternative.c:1995`
- `synchronize_srcu+0x131/0x170 sched_ext/kernel/rcu/srcutree.c:1467`
- `arch_jump_label_transform_queue+0x3e/0xa0 sched_ext/arch/x86/kernel/jump_label.c:136`
- ` bpf_struct_ops_map_free+0x5e/0x90 sched_ext/kernel/bpf/bpf_struct_ops.c:643`

With `CONFIG_DEFAULT_HUNG_TASK_TIMEOUT=140`, we don't think that this has to do with the scheduler inserted as sched_ext unregisters the scheduler if it holds a task for more than 30 seconds. From the report (appended below), it says to check for exiting tasks stuck between calls to exit_tasks_rcu_start() and exit_tasks_rcu_finish(). 

Commit version: https://github.com/sched-ext/sched_ext/commit/65c265174d11b9792840ff18f166dd8c4b89d9b0
Config file: [config.txt](https://github.com/sched-ext/sched_ext/files/14080629/config.txt)

No reproducers were found for this case. 

A sample report from task hung at `synchronize_srcu()` is shown below. Do let me know if you require further clarifications or the other reports as well! :)
```
tasks_rcu_exit_srcu_stall: rcu_tasks grace period number 13 (since boot) gp_state: RTGS_POST_SCAN_TASKLIST is 153635 jiffies old.
Please check any exiting tasks stuck between calls to exit_tasks_rcu_start() and exit_tasks_rcu_finish()
INFO: task rcu_tasks_kthre:13 blocked for more than 143 seconds.
      Not tainted 6.7.0-g65c265174d11 #7
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
task:rcu_tasks_kthre state:D stack:13920 pid:13    tgid:13    ppid:2      flags:0x00004000
Call Trace:
 <TASK>
 context_switch home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:5446 [inline]
 __schedule+0x3ff/0xfc0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6766
 __schedule_loop home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6841 [inline]
 schedule+0x44/0x140 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6856
 schedule_timeout+0x1bb/0x1d0 home/xingyi/fuzz/externals/sched_ext/kernel/time/timer.c:2143
 do_wait_for_common home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:95 [inline]
 __wait_for_common+0xbc/0x1e0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:116
 __synchronize_srcu+0xdb/0x1d0 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/srcutree.c:1388
 synchronize_srcu_expedited home/xingyi/fuzz/externals/sched_ext/kernel/rcu/srcutree.c:1413 [inline]
 synchronize_srcu+0x131/0x170 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/srcutree.c:1467
 rcu_tasks_postscan+0x5f/0x80 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:962
 rcu_tasks_wait_gp+0x2a2/0x6e0 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:765
 rcu_tasks_one_gp+0x7ae/0x820 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:589
 rcu_tasks_kthread+0x66/0x160 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:625
 kthread+0x1fa/0x250 home/xingyi/fuzz/externals/sched_ext/kernel/kthread.c:388
 ret_from_fork+0x48/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/process.c:147
 ret_from_fork_asm+0x1b/0x30 home/xingyi/fuzz/externals/sched_ext/arch/x86/entry/entry_64.S:242
 </TASK>
INFO: task kworker/1:0:22 blocked for more than 143 seconds.
      Not tainted 6.7.0-g65c265174d11 #7
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
task:kworker/1:0     state:D stack:11440 pid:22    tgid:22    ppid:2      flags:0x00004000
Workqueue: events kprobe_optimizer
Call Trace:
 <TASK>
 context_switch home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:5446 [inline]
 __schedule+0x3ff/0xfc0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6766
 __schedule_loop home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6841 [inline]
 schedule+0x44/0x140 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6856
 schedule_timeout+0x1bb/0x1d0 home/xingyi/fuzz/externals/sched_ext/kernel/time/timer.c:2143
 do_wait_for_common home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:95 [inline]
 __wait_for_common+0xbc/0x1e0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:116
 __wait_rcu_gp+0x19d/0x1a0 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/update.c:443
 synchronize_rcu_tasks_generic+0x90/0x120 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:642
 synchronize_rcu_tasks+0x14/0x20 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:1100
 kprobe_optimizer+0x2af/0x5f0 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:626
 process_one_work+0x50d/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2627
 process_scheduled_works home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2700 [inline]
 worker_thread+0x50b/0x950 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2781
 kthread+0x1fa/0x250 home/xingyi/fuzz/externals/sched_ext/kernel/kthread.c:388
 ret_from_fork+0x48/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/process.c:147
 ret_from_fork_asm+0x1b/0x30 home/xingyi/fuzz/externals/sched_ext/arch/x86/entry/entry_64.S:242
 </TASK>
INFO: task kworker/u4:4:136 blocked for more than 143 seconds.
      Not tainted 6.7.0-g65c265174d11 #7
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
task:kworker/u4:4    state:D stack:10736 pid:136   tgid:136   ppid:2      flags:0x00004000
Workqueue: netns cleanup_net
Call Trace:
 <TASK>
 context_switch home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:5446 [inline]
 __schedule+0x3ff/0xfc0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6766
 __schedule_loop home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6841 [inline]
 schedule+0x44/0x140 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6856
 schedule_preempt_disabled+0x10/0x20 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6913
 __mutex_lock_common home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:679 [inline]
 __mutex_lock+0x8bc/0xea0 home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:747
 mutex_lock_nested+0x16/0x20 home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:799
 arch_jump_label_transform_queue+0x3e/0xa0 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/jump_label.c:136
 __jump_label_update+0xe6/0x310 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:475
 jump_label_update+0x22c/0x280 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:829
 __static_key_slow_dec_cpuslocked.part.0+0x63/0x70 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:276
 __static_key_slow_dec_cpuslocked home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:271 [inline]
 __static_key_slow_dec home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:283 [inline]
 static_key_slow_dec+0x7e/0xb0 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:298
 nf_static_key_dec home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:392 [inline]
 __nf_unregister_net_hook+0x2a9/0x520 home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:515
 nf_unregister_net_hook home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:539 [inline]
 nf_unregister_net_hooks+0xde/0x110 home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:613
 ip6t_unregister_table_pre_exit+0x5c/0x70 home/xingyi/fuzz/externals/sched_ext/net/ipv6/netfilter/ip6_tables.c:1795
 ip6table_mangle_net_pre_exit+0x1c/0x30 home/xingyi/fuzz/externals/sched_ext/net/ipv6/netfilter/ip6table_mangle.c:92
 ops_pre_exit_list home/xingyi/fuzz/externals/sched_ext/net/core/net_namespace.c:160 [inline]
 cleanup_net+0x368/0x750 home/xingyi/fuzz/externals/sched_ext/net/core/net_namespace.c:602
 process_one_work+0x50d/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2627
 process_scheduled_works home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2700 [inline]
 worker_thread+0x50b/0x950 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2781
 kthread+0x1fa/0x250 home/xingyi/fuzz/externals/sched_ext/kernel/kthread.c:388
 ret_from_fork+0x48/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/process.c:147
 ret_from_fork_asm+0x1b/0x30 home/xingyi/fuzz/externals/sched_ext/arch/x86/entry/entry_64.S:242
 </TASK>
INFO: task scx_serialise:720 blocked for more than 143 seconds.
      Not tainted 6.7.0-g65c265174d11 #7
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
task:scx_serialise   state:D stack:11832 pid:720   tgid:720   ppid:271    flags:0x00004006
Call Trace:
 <TASK>
 context_switch home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:5446 [inline]
 __schedule+0x3ff/0xfc0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6766
 __schedule_loop home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6841 [inline]
 schedule+0x44/0x140 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6856
 schedule_preempt_disabled+0x10/0x20 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6913
 __mutex_lock_common home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:679 [inline]
 __mutex_lock+0x8bc/0xea0 home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:747
 mutex_lock_nested+0x16/0x20 home/xingyi/fuzz/externals/sched_ext/kernel/locking/mutex.c:799
 unregister_kprobes home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1852 [inline]
 unregister_kprobes home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1846 [inline]
 unregister_kprobe+0x22/0x90 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1842
 __unregister_trace_kprobe+0xf4/0x100 home/xingyi/fuzz/externals/sched_ext/kernel/trace/trace_kprobe.c:522
 destroy_local_trace_kprobe+0x9d/0x100 home/xingyi/fuzz/externals/sched_ext/kernel/trace/trace_kprobe.c:1844
 perf_kprobe_destroy+0xd7/0x100 home/xingyi/fuzz/externals/sched_ext/kernel/trace/trace_event_perf.c:293
 _free_event+0x206/0xd30 home/xingyi/fuzz/externals/sched_ext/kernel/events/core.c:5223
 put_event+0x45/0x60 home/xingyi/fuzz/externals/sched_ext/kernel/events/core.c:5320
 perf_event_release_kernel+0x45a/0x4e0 home/xingyi/fuzz/externals/sched_ext/kernel/events/core.c:5432
 perf_release+0x25/0x30 home/xingyi/fuzz/externals/sched_ext/kernel/events/core.c:5442
 __fput+0x1a3/0x6e0 home/xingyi/fuzz/externals/sched_ext/fs/file_table.c:394
 ____fput+0x15/0x20 home/xingyi/fuzz/externals/sched_ext/fs/file_table.c:422
 task_work_run+0x119/0x1b0 home/xingyi/fuzz/externals/sched_ext/kernel/task_work.c:180
 exit_task_work home/xingyi/fuzz/externals/sched_ext/./include/linux/task_work.h:38 [inline]
 do_exit+0x789/0x1900 home/xingyi/fuzz/externals/sched_ext/kernel/exit.c:869
 do_group_exit+0x82/0x170 home/xingyi/fuzz/externals/sched_ext/kernel/exit.c:1018
 get_signal+0x1ac2/0x1ad0 home/xingyi/fuzz/externals/sched_ext/kernel/signal.c:2904
 arch_do_signal_or_restart+0x30/0x440 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/signal.c:309
 exit_to_user_mode_loop home/xingyi/fuzz/externals/sched_ext/kernel/entry/common.c:168 [inline]
 exit_to_user_mode_prepare+0x185/0x200 home/xingyi/fuzz/externals/sched_ext/kernel/entry/common.c:204
 __syscall_exit_to_user_mode_work home/xingyi/fuzz/externals/sched_ext/kernel/entry/common.c:285 [inline]
 syscall_exit_to_user_mode+0x1a/0x50 home/xingyi/fuzz/externals/sched_ext/kernel/entry/common.c:296
 do_syscall_64+0x52/0x100 home/xingyi/fuzz/externals/sched_ext/arch/x86/entry/common.c:89
 entry_SYSCALL_64_after_hwframe+0x6e/0x76
RIP: 0033:0x7f661c8e7140
RSP: 002b:00007fff9f0ac3e8 EFLAGS: 00000202 ORIG_RAX: 0000000000000001
RAX: ffffffffffffffe0 RBX: 0000000000000017 RCX: 00007f661c8e7140
RDX: 0000000000000017 RSI: 00005639e029b7a0 RDI: 0000000000000001
RBP: 00005639e029b7a0 R08: 0000000000000000 R09: 0000000000000075
R10: 00007fff9f0ac3a4 R11: 0000000000000202 R12: 0000000000000017
R13: 00007f661c9c2760 R14: 0000000000000017 R15: 00007f661c9bd9e0
 </TASK>
INFO: task kworker/u4:5:1105 blocked for more than 143 seconds.
      Not tainted 6.7.0-g65c265174d11 #7
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
task:kworker/u4:5    state:D stack:11608 pid:1105  tgid:1105  ppid:2      flags:0x00004000
Workqueue: events_unbound bpf_map_free_deferred
Call Trace:
 <TASK>
 context_switch home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:5446 [inline]
 __schedule+0x3ff/0xfc0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6766
 __schedule_loop home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6841 [inline]
 schedule+0x44/0x140 home/xingyi/fuzz/externals/sched_ext/kernel/sched/core.c:6856
 schedule_timeout+0x1bb/0x1d0 home/xingyi/fuzz/externals/sched_ext/kernel/time/timer.c:2143
 do_wait_for_common home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:95 [inline]
 __wait_for_common+0xbc/0x1e0 home/xingyi/fuzz/externals/sched_ext/kernel/sched/completion.c:116
 __wait_rcu_gp+0x19d/0x1a0 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/update.c:443
 bpf_struct_ops_map_free+0x5e/0x90 home/xingyi/fuzz/externals/sched_ext/kernel/bpf/bpf_struct_ops.c:643
 bpf_map_free_deferred+0x129/0x360 home/xingyi/fuzz/externals/sched_ext/kernel/bpf/syscall.c:701
 process_one_work+0x50d/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2627
 process_scheduled_works home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2700 [inline]
 worker_thread+0x50b/0x950 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2781
 kthread+0x1fa/0x250 home/xingyi/fuzz/externals/sched_ext/kernel/kthread.c:388
 ret_from_fork+0x48/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/process.c:147
 ret_from_fork_asm+0x1b/0x30 home/xingyi/fuzz/externals/sched_ext/arch/x86/entry/entry_64.S:242
 </TASK>

Showing all locks held in the system:
1 lock held by rcu_tasks_kthre/13:
 #0: ffffffff84588f50 (rcu_tasks.tasks_gp_mutex){+.+.}-{3:3}, at: rcu_tasks_one_gp+0x55a/0x820 home/xingyi/fuzz/externals/sched_ext/kernel/rcu/tasks.h:581
5 locks held by kworker/1:0/22:
 #0: ffff888007068738 ((wq_completion)events){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #1: ffffc900000c3df8 ((optimizing_work).work){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #2: ffffffff845adf68 (kprobe_mutex){+.+.}-{3:3}, at: kprobe_optimizer+0x25/0x5f0 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:607
 #3: ffffffff84482790 (cpu_hotplug_lock){++++}-{0:0}, at: kprobe_optimizer+0x2a/0x5f0 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:608
 #4: ffffffff84491728 (text_mutex){+.+.}-{3:3}, at: kprobe_optimizer+0x38/0x5f0 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:609
1 lock held by khungtaskd/28:
 #0: ffffffff84589a40 (rcu_read_lock){....}-{1:2}, at: rcu_lock_acquire home/xingyi/fuzz/externals/sched_ext/./include/linux/rcupdate.h:301 [inline]
 #0: ffffffff84589a40 (rcu_read_lock){....}-{1:2}, at: rcu_read_lock home/xingyi/fuzz/externals/sched_ext/./include/linux/rcupdate.h:747 [inline]
 #0: ffffffff84589a40 (rcu_read_lock){....}-{1:2}, at: debug_show_all_locks+0x36/0x1e0 home/xingyi/fuzz/externals/sched_ext/kernel/locking/lockdep.c:6614
2 locks held by kworker/u4:3/41:
 #0: ffff888007068d38 ((wq_completion)events_unbound){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #1: ffffc9000015fdf8 ((work_completion)(&sub_info->work)){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
3 locks held by systemd-journal/88:
7 locks held by kworker/u4:4/136:
 #0: ffff8880070f8d38 ((wq_completion)netns){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #1: ffffc9000099bdf8 (net_cleanup_work){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #2: ffffffff84774710 (pernet_ops_rwsem){++++}-{3:3}, at: cleanup_net+0x73/0x750 home/xingyi/fuzz/externals/sched_ext/net/core/net_namespace.c:576
 #3: ffffffff8478c568 (nf_hook_mutex){+.+.}-{3:3}, at: __nf_unregister_net_hook+0x6e/0x520 home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:498
 #4: ffffffff84482790 (cpu_hotplug_lock){++++}-{0:0}, at: __static_key_slow_dec home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:282 [inline]
 #4: ffffffff84482790 (cpu_hotplug_lock){++++}-{0:0}, at: static_key_slow_dec+0x55/0xb0 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:298
 #5: ffffffff845ce408 (jump_label_mutex){+.+.}-{3:3}, at: jump_label_lock home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:27 [inline]
 #5: ffffffff845ce408 (jump_label_mutex){+.+.}-{3:3}, at: __static_key_slow_dec_cpuslocked.part.0+0x18/0x70 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:274
 #6: ffffffff84491728 (text_mutex){+.+.}-{3:3}, at: arch_jump_label_transform_queue+0x3e/0xa0 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/jump_label.c:136
1 lock held by scx_serialise/720:
 #0: ffffffff845adf68 (kprobe_mutex){+.+.}-{3:3}, at: unregister_kprobes home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1852 [inline]
 #0: ffffffff845adf68 (kprobe_mutex){+.+.}-{3:3}, at: unregister_kprobes home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1846 [inline]
 #0: ffffffff845adf68 (kprobe_mutex){+.+.}-{3:3}, at: unregister_kprobe+0x22/0x90 home/xingyi/fuzz/externals/sched_ext/kernel/kprobes.c:1842
2 locks held by kworker/u4:5/1105:
 #0: ffff888007068d38 ((wq_completion)events_unbound){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
 #1: ffffc900028bfdf8 ((work_completion)(&map->work)){+.+.}-{0:0}, at: process_one_work+0x450/0xc20 home/xingyi/fuzz/externals/sched_ext/kernel/workqueue.c:2602
1 lock held by syz-executor.0/1520:
 #0: ffffffff8478c568 (nf_hook_mutex){+.+.}-{3:3}, at: __nf_register_net_hook+0x10e/0x5d0 home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:432
1 lock held by scx_serialise/1969:
 #0: ffffffff84491728 (text_mutex){+.+.}-{3:3}, at: text_poke_copy+0x25/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/alternative.c:1972
1 lock held by syz-executor.0/1971:
 #0: ffffffff8478c568 (nf_hook_mutex){+.+.}-{3:3}, at: __nf_register_net_hook+0x10e/0x5d0 home/xingyi/fuzz/externals/sched_ext/net/netfilter/core.c:432
1 lock held by scx_serialise/2420:
 #0: ffffffff84491728 (text_mutex){+.+.}-{3:3}, at: text_poke_copy+0x25/0x60 home/xingyi/fuzz/externals/sched_ext/arch/x86/kernel/alternative.c:1972

=============================================
```

**Comment by htejun** [comment] 2024-01-30 16:51
Hello, first of all, thanks for the report.

From the dump, what seems to be happening is:

1.  Sombody is stuck while holding `jump_label_mutex` from `__static_key_slow_dec_cpuslocked()`:
```
#5: ffffffff845ce408 (jump_label_mutex){+.+.}-{3:3}, at: jump_label_lock home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:27 [inline]
 #5: ffffffff845ce408 (jump_label_mutex){+.+.}-{3:3}, at: __static_key_slow_dec_cpuslocked.part.0+0x18/0x70 home/xingyi/fuzz/externals/sched_ext/kernel/jump_label.c:274
```
2. Someone else (`kworker/u64:4:136`) gets stuck waiting for the mutex too.
3. The system becomes generally unhappy with tasks stuck in uninterruptible sleeps.

Would it be possible to either take backtraces of all tasks or a crashdump afterwards? Here, without seeing who's holding the `jump_label_mutex` with what backtrace, I can't tell why it's happening.

**Comment by xingyiz** [comment] 2024-01-31 17:01
Hello @htejun, thank you for your quick response and my sincere apologies for the lack of information provided. I have attached the log files here, which contain information about the tasks and their respective backtraces along with the locks that each task holds. I have also attached their corresponding reports (which are similar to the one I pasted above). I hope this helps! :)

`jump_label_mutex` seems to only be held by one task though. Could it be `pack_mutex` or `text_mutex` instead? 

[log4.txt](https://github.com/sched-ext/sched_ext/files/14114689/log4.txt)
[log8.txt](https://github.com/sched-ext/sched_ext/files/14114690/log8.txt)
[log32.txt](https://github.com/sched-ext/sched_ext/files/14114691/log32.txt)
[report4.txt](https://github.com/sched-ext/sched_ext/files/14114692/report4.txt)
[report8.txt](https://github.com/sched-ext/sched_ext/files/14114694/report8.txt)
[report32.txt](https://github.com/sched-ext/sched_ext/files/14114696/report32.txt)

**Comment by htejun** [comment] 2024-02-01 00:30
The logs you posted don't seem to contain more information. So, what the current dumps are showing is 1. some tasks are stuck for a long time 2. their stack traces 3. who's holding what locks in the system. It doesn't show the backtraces of the tasks that are holding the locks from 3, which is what we need.

So, can you please either trigger sysrq-t or, if the system is alive enough, do `cat /proc/PID/stack` of the tasks that are holding the locks? The dump doesn't show the pid of the tasks that are holding the locks for some reason, so it might involve a bit of digging to map the holders to the pids.

**Comment by xingyiz** [comment] 2024-02-04 12:59
Hello! So sorry for misunderstanding your request. 

I can't seem to trigger sysrq-t after the task hung dump as it would lose connection with the VM (and I can't retrieve the output), so I triggered it after I see the following task hung message instead. 
```
[  267.677840] tasks_rcu_exit_srcu_stall: rcu_tasks grace period number 13 (since boot) gp_state: RTGS_POST_SCAN_TASKLIST is 92126 jiffies old.
[  267.679469] Please check any exiting tasks stuck between calls to exit_tasks_rcu_start() and exit_tasks_rcu_finish()
```

`scx_serialise/715` (my scheduler) and `syz-executor/264` are the processes that have`do_exit` in their stack trace, so I figured they were the reasons for the exiting tasks being stuck. As I do add a kprobe to `do_exit` in my scheduler, I did a test and removed the kprobe, and there were no further task hungs being reported by the system. Running my scheduler in a VM instance (i.e. not a VM spawned by syzkaller) does not give such errors though, so I suspect there might be some conflict between my scheduler and syzkaller?

I've attached the relevant files here:
- The output of sysrq-t
- The report provided by syzkaller
- My `do_exit` kprobe program. 

[do_exit.txt](https://github.com/sched-ext/sched_ext/files/14156837/do_exit.txt)
[report.txt](https://github.com/sched-ext/sched_ext/files/14156838/report.txt)
[sysrq-t.txt](https://github.com/sched-ext/sched_ext/files/14156839/sysrq-t.txt)

It doesn't seem to be a sched_ext issue actually, so please feel free to close this issue if you wish :) Though any debugging assistance would be greatly appreciated (if it doesn't take too much of your time). Thank you for your help!

**Comment by htejun** [comment] 2024-02-04 21:44
Hmm... from scx core side, the followings should always hold no matter what the scheduler implementation does:

- The scx hang watchdog should be able to recover the system if a task becomes runnable but fails to run for too long.
- sysrq-S should always be able to recover the system.

So, if you can reproduce the problem and the system can't be restored with `sysrq-S`, that's a bug in the scx core (provided that the same problem can't be reproduced without scx, that is).

I'm going to close the issue for now but please feel free to reopen or file a new issue if this is a scx core issue. Thanks.

**Closed as completed by htejun** 2024-02-04 21:44 UTC
